# Header
menu:
  Home: /
  Archives: /archives
  Pages: /pages
rss: /atom.xml

# Content
excerpt_link: Read More
no_title: (no title)
fancybox: true

# Sidebar
sidebar: right
widgets:
- archive
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
fb_type: website
