# Header
menu:
  Home: /
  Archives: /archives
  Pages: /pages
  Sublevel test:
    LINK: /archives
    Under: /under
    Under2: /archives
  After sub: /aftersub
  Archives1: /archives
  Pages1: /pages
  Sublevel:
    LINK: /testlevel2
    Under: /under
    Under21: /foo
    1Under1: /foo
    2Under1: /foo
    3Under1: /foo
    1Under21: /foo
    2Under21: /foo
    3Under21: /foo
  After sub2: /aftersub
rss: /atom.xml

# Content
excerpt_link: Read More
no_title: (no title)
fancybox: true

# Sidebar
sidebar: right
widgets:
- connection_information
- links
- archive
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
fb_type: website
